<?xml version="1.0"?>

<robot name="kubo" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find tractor_sim_description)/urdf/kubo.gazebo"/>
  <xacro:include filename="$(find tractor_sim_description)/urdf/kubo_materials.urdf.xacro"/>
  <xacro:include filename="$(find tractor_sim_description)/urdf/kubo_macros.urdf.xacro"/>

  <!-- Degree-to-radian conversions -->
  <xacro:property name="degrees_45" value="0.785398163"/>
  <xacro:property name="degrees_90" value="1.57079633"/>

  <!-- chassis_length is measured along the x axis, chassis_width
       along the y axis, and chassis_height along the z axis.
      Note: Size of chassis won't affect wheel position or function-->
  <xacro:property name="chassis_length" value="1.5"/>
  <xacro:property name="chassis_width" value="0.6"/>
  <xacro:property name="chassis_height" value="0.1"/>
  <xacro:property name="chassis_mass" value="2.788"/>
  <xacro:property name="chassis_offset" value=".25"/> <!-- Z Distance from ground -->

  <!-- hub_dia and tire_dia are the diameters of the hub and tire,
       respectively. hex_hub_depth is the distance that the hex hub is
       inset from the outer edge of the tire. It is set so that each wheel
       is a "zero offset" wheel. hex_hub_depth = tire_width / 2 -
       axle_length. -->
  <xacro:property name="hub_dia" value="0.09652"/> <!-- ? -->

  <xacro:property name="ftire_dia" value="0.5"/>
  <xacro:property name="ftire_width" value="0.15"/>
  <xacro:property name="fhex_hub_depth" value="${ftire_width / 2 - axle_length}"/> <!-- tire_width / 2 - axle_length-->
  <xacro:property name="fwheel_mass" value="0.29"/>

  <xacro:property name="btire_dia" value="0.7"/>
  <xacro:property name="btire_width" value="0.2"/>
  <xacro:property name="bhex_hub_depth" value="${btire_width / 2 - axle_length}"/> <!-- tire_width / 2 - axle_length-->
  <xacro:property name="bwheel_mass" value="0.29"/>

  <!-- hex_hub_dist is the distance between left and right hex hubs when
       the shock absorbers are fully extended. axle_length is the distance
       from a U joint to the corresponding hex hub. wheel_travel is the
       vertical wheel travel. -->
  <xacro:property name="wheelbase" value="1.5"/>
  <xacro:property name="hex_hub_dist" value="1.4"/> <!-- ? -->
  <xacro:property name="axle_length" value="0.3"/> <!-- ? -->
  <xacro:property name="wheel_travel" value="0"/>
  <xacro:property name="shock_z_offset" value="0.0655"/>

  <!-- shock_eff_limit is 2 * ((shock_stroke / 2) * shock_spring_constant) N.
       shock_stroke is 0.028575 meters. shock_spring_constant, an approximation
       of a Traxxas Ultra Shock shock absorber spring's constant, is
       437.817 N/m. -->
  <xacro:property name="shock_eff_limit" value="125106"/>
  <xacro:property name="shock_vel_limit" value="1000000"/>

  <!-- The specifications for a Titan(R) 550 motor could not be found, so the
       stall torque of a Mabuchi Motor(R) RS-550VC-7525 motor was used instead.
       num_spur_gear_teeth = 68
       num_pinion_gear_teeth = 19
       final_gear_ratio = (num_spur_gear_teeth / num_pinion_gear_teeth) *
         5.22 = 18.68
       stall_torque = 0.549 N m
       axle_eff_limit = ((2 * stall_torque) * final_gear_ratio) / 4 =
         5.12766 N m
       max_speed = 40 mph (30+ mph) = 17.8816 m/s
       axle_vel_limit = (2 * pi) * (max_speed / (pi * tire_dia)) =
         244.8696 rad/s -->
  <xacro:property name="axle_eff_limit" value="512766"/>
  <xacro:property name="axle_vel_limit" value="2448696"/>

  <!-- These constants are used to simulate a Traxxas 2056 servo operated at
       6 V. servo_stall_torque is measured in N m. servo_no_load_speed is
       measured in rad/s. -->
  <xacro:property name="servo_stall_torque" value="5649"/>
  <xacro:property name="servo_no_load_speed" value="4553"/>

  <xacro:property name="sensorSize" value="0.05"/> <!--TODO: Get rid of this -->
  <xacro:property name="sensorMass" value="0.1"/>



  <!-- base_link must have geometry so that its axes can be displayed in
       rviz. -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="chassis_mat"/>
    </visual>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Chassis -->
  <link name="chassis">
    <visual>
      <origin xyz="${chassis_length / 2} 0 ${chassis_offset}"/> <!--Defualt: 0 0 ${-chassis_height / 2} -->
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="chassis_mat"/>
    </visual>

    <collision>
      <origin xyz="${chassis_length / 2} 0 ${chassis_offset}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

    <xacro:solid_cuboid_inertial
        width="${chassis_length}" depth="${chassis_width}"
        height="${chassis_height}" mass="${chassis_mass}">
      <origin xyz="0 0 ${-chassis_height / 2}"/>
    </xacro:solid_cuboid_inertial>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="base_link_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>


  <!-- Wheels -->
  <xacro:front_wheel lr_prefix="left" fr_prefix="front"
                     lr_reflect="1" fr_reflect="1"/>
  <xacro:front_wheel lr_prefix="right" fr_prefix="front"
                     lr_reflect="-1" fr_reflect="1"/>
  <xacro:rear_wheel lr_prefix="left" fr_prefix="rear"
                    lr_reflect="1" fr_reflect="-1"/>
  <xacro:rear_wheel lr_prefix="right" fr_prefix="rear"
                    lr_reflect="-1" fr_reflect="-1"/>

  <!-- Sensors -->
  <!-- IMU approximate
https://github.com/olinrobotics/gravl/wiki/Kubo:-Transforms-->
  <xacro:sensor sensor_name="camera"
                x_pos="2.08" y_pos="0" z_pos="1.04"
                x_rot="0" y_rot="0" z_rot="0"/>
  <xacro:sensor sensor_name="hokuyo"
                x_pos="2.02" y_pos="0" z_pos="1.19"
                x_rot="0" y_rot="0.157" z_rot="0"/>
  <xacro:sensor sensor_name="imu"
                x_pos="-0.3" y_pos="0" z_pos="1"
                x_rot="0" y_rot="0" z_rot="0"/>
  <xacro:sensor sensor_name="hemisphere_gps"
                x_pos="1.94" y_pos="0" z_pos="1.49"
                x_rot="0" y_rot="0" z_rot="0"/>
  <xacro:sensor sensor_name="rtk_gps"
                x_pos="0.3" y_pos="0" z_pos="2.21"
                x_rot="0" y_rot="0" z_rot="0"/>
  <!-- Hokuyo Laser -->
  <!-- Using mesh example
  <link name="hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://tractor_sim_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=".15 0 .6" rpy="0 -.1 0"/>
    <parent link="chassis"/>
    <child link="hokuyo"/>
  </joint>
-->


</robot>
